### ISSUE TITLE
already unmounted card

### ISSUE THREAD

**Issue by ghost** [exaviorn/RasPiWrite#4]
I'm getting this error.  I ran the script once, it unmounted my SD card, then it wasn't happy with the distro image i gave it, so i ran it again and i think the problem is that the sd card was already unmounted.

```
It is advisable to remove any other USB HDDs or memory sticks, the wizard might select that one,  if you have multiple hard drives installed, please take a LOT of care selecting the right drive 
Now enter your SD Card, press enter when you are ready...


---------------------------------------------------------
The following drives were found:

Filesystem      Size   Used  Avail Capacity  Mounted on

Volumes/BOOTCAMP
---------------------------------------------------------

Traceback (most recent call last):
  File "raspiwrite.py", line 423, in <module>
    SD = matchSD(volumes).group(1) #selects the first SD/USB drive located
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by exaviorn** [comment]
Simply pull out the SD card and insert it again to re-mount it, I'm afraid this will happen every time something fails in the RaPiWrite script, as unmounting the SD card for writing is one of the first stages in the writing progress.

You might be having problems with the distro image if it isn't currently supported (Debian, Arch, Fedora and QtonPi are currently the only supported distros), you can make RasPiWrite support it by following the 'Own Image Requirements' section at exaviorn.com/raspiwrite, raw .img support is being added shortly

**Comment by abepetrillo** [comment]
Hmmm, script seems to have nuked my SD Card. I to have the same probem, ran it once, it found the card but I aborted the script before choosing a distro. Re-inserted card and there's no response on Mac or Windows
