### ISSUE TITLE
raspiwrite syntax error

### ISSUE THREAD

**Issue by ethanculler** [exaviorn/RasPiWrite#50]
When I follow the execution instructions I get this:

bakaster$ python raspiwrite.py 
  File "raspiwrite.py", line 177
    else
       ^
SyntaxError: invalid syntax

**Comment by Ciaran0** [comment]
I get the same error

**Comment by soswow** [comment]
same here.

**Comment by ethanculler** [comment]
I dug into this a little more, fixed a couple syntax issues locally, but haven't gotten this to run yet.

**Comment by ethanculler** [comment]
Looks like this is a duplicate of some earlier issues. The issue created by balsama appears to have a commit for fixed code.
